# app deployment
# @param app.name - name of deployment
# @param app.replicaCount - amount of app pod replicas
# @param app.image - application image
# @param app.port - app containers port
app: 
  name: app
  replicaCount: 1
  image: talefraim25/tal:latest
  port: 3000

# app service
# @param app.type - type of the app service to accses application
# @param app.port - port the service assigned to, able to connect to localhost:port 
app_service:
  type: LoadBalancer
  port: 3000

# mongo deployment
# @param mongo.name - name of deployment
# @param mongo.replicaCount - amount of mongo pod replicas
# @param mongo.image - mongo image
# @param mongo.port - mongo containers port
mongo:
  name: mongo
  replicaCount: 1
  image: mongo
  port: 27017

# mongo service
# @param mongo.type - type of the mongo service to cluster
# @param mongo.port - port the service assigned to
mongo_service:
  type: ClusterIP
  port: 27017